// <auto-generated />
using ApiGastos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGastos.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260219140414_CorrecaoDataNascimento")]
    partial class CorrecaoDataNascimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiGastos.Models.Categoria", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("FinalidadeId")
                        .HasColumnType("int");

                    b.HasKey("Identificador");

                    b.HasIndex("FinalidadeId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ApiGastos.Models.Finalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Finalidade");
                });

            modelBuilder.Entity("ApiGastos.Models.Pessoa", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Identificador");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ApiGastos.Models.Transacao", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("PessoaIdentificador")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Identificador");

                    b.HasIndex("PessoaIdentificador");

                    b.HasIndex("TipoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("CategoriaTransacao", b =>
                {
                    b.Property<int>("CategoriaIdentificador")
                        .HasColumnType("int");

                    b.Property<int>("TransacaoIdentificador")
                        .HasColumnType("int");

                    b.HasKey("CategoriaIdentificador", "TransacaoIdentificador");

                    b.HasIndex("TransacaoIdentificador");

                    b.ToTable("CategoriaTransacao");
                });

            modelBuilder.Entity("ApiGastos.Models.Categoria", b =>
                {
                    b.HasOne("ApiGastos.Models.Finalidade", "Finalidade")
                        .WithMany()
                        .HasForeignKey("FinalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finalidade");
                });

            modelBuilder.Entity("ApiGastos.Models.Transacao", b =>
                {
                    b.HasOne("ApiGastos.Models.Pessoa", "Pessoa")
                        .WithMany("Transacao")
                        .HasForeignKey("PessoaIdentificador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGastos.Models.Finalidade", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("CategoriaTransacao", b =>
                {
                    b.HasOne("ApiGastos.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaIdentificador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGastos.Models.Transacao", null)
                        .WithMany()
                        .HasForeignKey("TransacaoIdentificador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiGastos.Models.Pessoa", b =>
                {
                    b.Navigation("Transacao");
                });
#pragma warning restore 612, 618
        }
    }
}
